### ISSUE TITLE
Add captions to the diagram icons on `README.md`

### ISSUE THREAD

**Issue by micalevisk** [eugene-manuilov/typeorm-uml#16]
since the icon meanings aren't standard, can you please add something like this:

| Character | Icon | Description |
|:---------:|:----:|:------------|
| `-`       | ![](https://s.plantuml.com/img/private-field.png) | (_not used thus you can get rid of this row_)
| `#`       | ![](https://s.plantuml.com/img/protected-field.png) | (?? _I'm not sure about this one_)
| `~`       | ![](https://s.plantuml.com/img/package-private-field.png) | unique column
| `+`       | ![](https://s.plantuml.com/img/public-field.png) | primary key column

**Comment by eugene-manuilov** [comment]
Yeah, unfortunately, I still can't find good icons for it... Will give it another try in the next days, maybe I will find something... If not, will just add this table to the readme file.

> \# (?? I'm not sure about this one)

It's a column that is included in a non-unique index :smile:

**Comment by eugene-manuilov** [comment]
Ok, i have managed to update icons. Hope it looks okay now.

<details><summary>Regular mode</summary>

[![regular](http://www.plantuml.com/plantuml/png/pLTXRzis4FskNy5Xm6032sfdo0OKWb6rSLfZZWTash1z6cZnB14MUThnLDjOyjydqKudknMz01ao-TkzztZYkpkHVkDO4jUcZAAl5Aoq1L6jOJVO3aMydCGPbaYlhoMjtsEfmDwXciJVD8H9_CfZ4x6DNoqddyIhW_YW_3hnpsUQJ_mcK1lRLKnlsb-ZCA2ql238aDINf2oN9RHAiAnv9xOYZiKW_NPJQ8QXc4oYgD0AX6CWGDvLuFO10roWSb74M0b6iKHcD4Bf9XThj95RQrj9aaOGrbPbI1P8N7NYfRRGhYYGchKwW2kamesskLZ9qa47AQHL6zBCO3_3ib8w9_wAHFEybTawztdVjJiMVZiUIOXmimywa3a1sBq2IG6T00zHj3T8L8IgpbWCVG9VNQ6L6BuMRsVlPujqS3aQYWPPUQHsGBDJD8vlVcpy58_b4govX9RqQtBtxaDoD_ZXQYWwk06MwIbdF1eTaLnPvq6yDaRIhgMaiyNlwVItj0jx_nlivzjaFc_VzFjZzReEBLwHphpyPlvJaWx6bqUeqYx3sd8luSzQ-guBlK21rUExj-Zu2Cq898DAV8hh99scizjfbr1NAaoewcMfNH6Y-E5s_JXO5K0pj0pMmzxxJa_vZlj3CvX_sLQ79kplB4_RhzjFUldQFa_rmkOoIUka_nGzoz0-oTeCLN1epqoTGHM27KkktKiPworurk-W0-SqsfaAMePhi272MLTSlKoHPTdRikqaNf_hQvRRNimLkggqpVl5mVmLeS7k5gz6JvkvdAHLuJskD3bUI0E1F4OhLS8PKYdFhuDBVN9u7HzmOAGkGpcqXV4P_3A0Pvft0RZn-wEsMMWBtcyABFBVpbhjmgFs_oqjuHwUBdwvVKh9A-dS1abzaAxeqhuxRcEfZBRzzuAFO1LIFqwGQyT0WR9u5-QOQzj7q9O9--vL5U7AEzGfwkCTyk7-ukB-tXStwjm13k4cyiNuGHrr3xQkv1WuJI4Uy9z8z0QiydzN_WO0)](http://www.plantuml.com/plantuml/uml/pLTXRzis4FskNy5Xm6032sfdo0OKWb6rSLfZZWTash1z6cZnB14MUThnLDjOyjydqKudknMz01ao-TkzztZYkpkHVkDO4jUcZAAl5Aoq1L6jOJVO3aMydCGPbaYlhoMjtsEfmDwXciJVD8H9_CfZ4x6DNoqddyIhW_YW_3hnpsUQJ_mcK1lRLKnlsb-ZCA2ql238aDINf2oN9RHAiAnv9xOYZiKW_NPJQ8QXc4oYgD0AX6CWGDvLuFO10roWSb74M0b6iKHcD4Bf9XThj95RQrj9aaOGrbPbI1P8N7NYfRRGhYYGchKwW2kamesskLZ9qa47AQHL6zBCO3_3ib8w9_wAHFEybTawztdVjJiMVZiUIOXmimywa3a1sBq2IG6T00zHj3T8L8IgpbWCVG9VNQ6L6BuMRsVlPujqS3aQYWPPUQHsGBDJD8vlVcpy58_b4govX9RqQtBtxaDoD_ZXQYWwk06MwIbdF1eTaLnPvq6yDaRIhgMaiyNlwVItj0jx_nlivzjaFc_VzFjZzReEBLwHphpyPlvJaWx6bqUeqYx3sd8luSzQ-guBlK21rUExj-Zu2Cq898DAV8hh99scizjfbr1NAaoewcMfNH6Y-E5s_JXO5K0pj0pMmzxxJa_vZlj3CvX_sLQ79kplB4_RhzjFUldQFa_rmkOoIUka_nGzoz0-oTeCLN1epqoTGHM27KkktKiPworurk-W0-SqsfaAMePhi272MLTSlKoHPTdRikqaNf_hQvRRNimLkggqpVl5mVmLeS7k5gz6JvkvdAHLuJskD3bUI0E1F4OhLS8PKYdFhuDBVN9u7HzmOAGkGpcqXV4P_3A0Pvft0RZn-wEsMMWBtcyABFBVpbhjmgFs_oqjuHwUBdwvVKh9A-dS1abzaAxeqhuxRcEfZBRzzuAFO1LIFqwGQyT0WR9u5-QOQzj7q9O9--vL5U7AEzGfwkCTyk7-ukB-tXStwjm13k4cyiNuGHrr3xQkv1WuJI4Uy9z8z0QiydzN_WO0)
</details>


<details><summary>Monochrome mode</summary>

[![monochrome](http://www.plantuml.com/plantuml/png/pLTXJ_Cs4FwUN-7fbQPM6dfR9ZO9HHNTQA5QwIIMJTkdoOslZTNObvtFq6hmtzSabAM5k4DYueLlzpoFptxkBdOl74jYR_8e-ah1GbiGnGesdNLNnFD1d6AET7ufQNM5kG9xYseGVxqb3EBF5JOGw_ZpVF0iNkp4jVBJiFfxeNdcRmFUsAPYD2x_jme3IiiJWXH9lIPbES-XL89bpHkn5d4iEiatdyRZCcTN30PHb6a5mZ4G86yAS7N006UeN1Gn5e9Hp94PZL2Q86MDDd8hRGj9qWX2RrMAP874MIEUQmlbYWA9Csm0BfCAxxLTYeNC7JIGJ5frJvePx0lCeCKq8pGWc3n4KNqwKH0gdxBeYhyZKPT6Q2Mwv-A7oTLabdHEUrqHYTftuHtGv12Du_5FMol4pcl1cdCeIRyDRt-y7jvslZ_hYWPkW6LooEdtUdiab_jb4FV6IDgKb6Go-oCP_PuquTAw4llbPZYTbZlzRb-zyg752z9f9HzFVnucdVxf7ggqIz5RRYNyvMNTCe4DP5ZizbwY_Jqq9P0CQbYbk1mcesHoCseIVA72XCBFS-so4AMQJDUEWrK1D4NBK7jGU__ut5D82kXFpM3-OrizDM5hPzMqUjrsqiVNzdsg5pQNILedgw_8kmpjcwnDKGM6zkZK6LGXsB5axpx8sDg2T_qEEd1Eevsee6Mu0XiY77N5-Nc2BFFMbYqdyV9ONxDSjs8kqqMXxR9T7CnV41fi7l6izxQPMvAqAdp6XIR7CsaWaCTefN8uGihbyNLmhWykh_qB3epKUIY7jj0_Wfy6y5Jp9W0NX7VQfg4ZL7vJQ97_TTQy2u_QbrjQmXeUpNwzUKl92-dSFPAwbYvhqhxTRsEfZBRjxu8xi0gf7ITOQiT0eRAKBanngMqRGLicR7jN5OIBqg5cKNTloCU7avE7XwguKUCDy1Gk8w_5dzHHys9hIlQ1mnJY4V-DH1TWLVLRuny0)](http://www.plantuml.com/plantuml/uml/pLTXJ_Cs4FwUN-7fbQPM6dfR9ZO9HHNTQA5QwIIMJTkdoOslZTNObvtFq6hmtzSabAM5k4DYueLlzpoFptxkBdOl74jYR_8e-ah1GbiGnGesdNLNnFD1d6AET7ufQNM5kG9xYseGVxqb3EBF5JOGw_ZpVF0iNkp4jVBJiFfxeNdcRmFUsAPYD2x_jme3IiiJWXH9lIPbES-XL89bpHkn5d4iEiatdyRZCcTN30PHb6a5mZ4G86yAS7N006UeN1Gn5e9Hp94PZL2Q86MDDd8hRGj9qWX2RrMAP874MIEUQmlbYWA9Csm0BfCAxxLTYeNC7JIGJ5frJvePx0lCeCKq8pGWc3n4KNqwKH0gdxBeYhyZKPT6Q2Mwv-A7oTLabdHEUrqHYTftuHtGv12Du_5FMol4pcl1cdCeIRyDRt-y7jvslZ_hYWPkW6LooEdtUdiab_jb4FV6IDgKb6Go-oCP_PuquTAw4llbPZYTbZlzRb-zyg752z9f9HzFVnucdVxf7ggqIz5RRYNyvMNTCe4DP5ZizbwY_Jqq9P0CQbYbk1mcesHoCseIVA72XCBFS-so4AMQJDUEWrK1D4NBK7jGU__ut5D82kXFpM3-OrizDM5hPzMqUjrsqiVNzdsg5pQNILedgw_8kmpjcwnDKGM6zkZK6LGXsB5axpx8sDg2T_qEEd1Eevsee6Mu0XiY77N5-Nc2BFFMbYqdyV9ONxDSjs8kqqMXxR9T7CnV41fi7l6izxQPMvAqAdp6XIR7CsaWaCTefN8uGihbyNLmhWykh_qB3epKUIY7jj0_Wfy6y5Jp9W0NX7VQfg4ZL7vJQ97_TTQy2u_QbrjQmXeUpNwzUKl92-dSFPAwbYvhqhxTRsEfZBRjxu8xi0gf7ITOQiT0eRAKBanngMqRGLicR7jN5OIBqg5cKNTloCU7avE7XwguKUCDy1Gk8w_5dzHHys9hIlQ1mnJY4V-DH1TWLVLRuny0)
</details>

Let me know if it works or I need to change something, otherwise, will ship it with the next release.

**Comment by micalevisk** [comment]
looks greate to me :ok_hand:

**Comment by eugene-manuilov** [comment]
The new version `1.4.0` has been published and this feature has been shipped. Thanks, @micalevisk! :tada:
